version: '2'
services:

  elasticsearch:
    build: elasticsearch
    ports:
     - "9200:9200"
     - "9300:9300"
    volumes:
     - /data:/data

  logstash:
    build: logstash
    ports:
     - "5044:5044"
    depends_on:
     - elasticsearch
    links:
     - elasticsearch

  kibana:
    build: kibana
    ports: 
     - "5601:5601"
    links:
     - elasticsearch

  nginx:
    build: nginx
    ports:
     - "80:80"
    environment:
     - UPSTREAM_HOST=kibana
     - UPSTREAM_PORT=5601
    depends_on:
     - kibana
    command: /bin/bash -c "envsubst '$$UPSTREAM_HOST $$UPSTREAM_PORT' < /tmp/nginx.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

